name: Commit cheat

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 1/2 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Modify last update
        run: |
          cat > LAST_UPDATED
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "raexera@gmail.com"
          git config --local user.name "raexera"
          git add --all
          git commit -m "reforestation"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
